AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msBundleMedicalInfo
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msBundleMedicalInfo/dev/1604180625791-2020-10-31T21:43:45.791Z/msBundleMedicalInfo.zip
      FunctionName: msBundleMedicalInfo
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      Runtime: nodejs12.x
      Timeout: 30
      Description: Microservi?o que insere um recurso no DW
      Tags:
        - Key: api
          Value: ESBSamihealth
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:fhirOmopConverter:103'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:lodash:2'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:21'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:32'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:uuid:1'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionyQOSFqJj8kekwwUwI0cl1gFpMUaeuwwIpSXSntCGfCA:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: u6VIXLdyBbdijrXfozfZeN6KeH3XJ1lmTpH2MT0QsfI=
      Description: Microservi?o que insere um recurso no DW
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionyQOSFqJj8kekwwUwI0cl1gFpMUaeuwwIpSXSntCGfCA
