AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msCreateGympassPractice
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msCreateGympassPractice/dev/1608133692868-2020-12-16T15:48:12.868Z/msCreateGympassPractice.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msCreateGympassPractice
      MemorySize: 128
      Timeout: 30
      Description: Microservi?o que insere uma treino de um colaborador Gympass
      Tags:
        - Key: api
          Value: ESBSamihealth
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:fhirOmopConverter:126'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:lodash:2'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:47'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:uuid:1'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:29'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionFIyF21aoOwLbvAYpOegQXBHXFwmXDZmUs6Ahm2idc:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: YS0TmRFj8QqV/ggo6PHrqCevI8V6SWrdUDFDapZqAf4=
      Description: Microservi?o que insere uma treino de um colaborador Gympass
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionFIyF21aoOwLbvAYpOegQXBHXFwmXDZmUs6Ahm2idc
