AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msCreateGympassPractice
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msCreateGympassPractice/dev/1617706522702-2021-04-06T10:55:22.702Z/msCreateGympassPractice.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msCreateGympassPractice
      MemorySize: 128
      Timeout: 30
      Description: Microservi?o que insere uma treino de um colaborador Gympass
      Tags:
        - Key: api
          Value: ESBSamihealth
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:47'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:uuid:1'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersion2kDGfgZ09cI4oiVutxd8dKKxK6akXZpamR2xS3MoP0E:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: qeqdblkL7GDXxsUkokRUELca7LMR5Z0rV5Ep7eDj5s8=
      Description: Microservi?o que insere uma treino de um colaborador Gympass
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersion2kDGfgZ09cI4oiVutxd8dKKxK6akXZpamR2xS3MoP0E
