AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msCreateDWData
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msCreateDWData/dev/1621523545488-2021-05-20T15:12:25.488Z/msCreateDWData.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msCreateDWData
      MemorySize: 128
      Timeout: 60
      Description: Microservi?o que grava dados no DW
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:29'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:47'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:dataMapping:67'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionZiWa0aX6ZKAiI6BPA3P70kReOUYENRSwmWaGgDlo:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: 010TpJ3hMHm721iAaWtImt4bnVbHDPIV/TE3cfptMss=
      Description: Microservi?o que grava dados no DW
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionZiWa0aX6ZKAiI6BPA3P70kReOUYENRSwmWaGgDlo
