AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msGetMedicalInfo
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msGetMedicalInfo/dev/1621350724853-2021-05-18T15:12:04.853Z/msGetMedicalInfo.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msGetMedicalInfo
      MemorySize: 2048
      Timeout: 120
      Description: Microservi?o que l? um recurso do DW
      Tags:
        - Key: api
          Value: ESBSamihealth
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:fhirOmopConverter:146'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:lodash:2'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:62'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:path:1'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:31'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionwVfOKbkf5WJQtLvX12RD843Zo9eHrcuDAcVkbtofbQ:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: WmuyGX36rAONyq/yOY2WPoMvYq7sPZPxEmzOoU3ilpI=
      Description: Microservi?o que l? um recurso do DW
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionwVfOKbkf5WJQtLvX12RD843Zo9eHrcuDAcVkbtofbQ
