AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msCreateIsalabData
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msCreateIsalabData/dev/1626358684498-2021-07-15T14:18:04.498Z/msCreateIsalabData.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msCreateIsalabData
      MemorySize: 256
      Timeout: 60
      Description: Microservi?o que envia os dados para a Isalab
      Tags:
        - Key: api
          Value: ESBSamihealth
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:63'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:35'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:dataTransform:1'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:nodeFetch:2'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionD5D7EK2AzULQ8h0D7HU17tUkbb2EawrE1AjWLSpQA:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: PCxOrvZTlxmsRieCwn6IZTPe5pAY8fdkBKHTjS7lX2U=
      Description: Microservi?o que envia os dados para a Isalab
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionD5D7EK2AzULQ8h0D7HU17tUkbb2EawrE1AjWLSpQA
