AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msImportDW
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msImportDW/dev/1636034730563-2021-11-04T14:05:30.563Z/msImportDW.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msImportDW
      MemorySize: 128
      Timeout: 30
      Description: Microservi?o que insere um recurso no DW
      Tags:
        - Key: api
          Value: ESBSamihealth
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:66'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:nodeFetch:2'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionO06WG51NtvaUeSxwzCYIjNppiFgRPgeBKV78s439Y8:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: ZTIxod6HWpXQNe+jKY1Ugo6TDZ/J6H19geHudDtH77c=
      Description: Microservi?o que insere um recurso no DW
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionO06WG51NtvaUeSxwzCYIjNppiFgRPgeBKV78s439Y8
