AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msCreateMVData
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msCreateMVData/dev/1621348247425-2021-05-18T14:30:47.425Z/msCreateMVData.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msCreateMVData
      MemorySize: 256
      Timeout: 60
      Description: Microservi?o que grava a empresa na MV
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:models:40'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:47'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:dataTransform:2'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionpuXaRLAxTKIYDIbesAM81p2p4unvd5aCvAFH7mdnxU:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: OeX//5pt8u94eMZMKPRxQPof7J+U7LdUunYev1/W4og=
      Description: Microservi?o que grava a empresa na MV
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
    Export:
      Name: sls-msCreateMVData-dev-ServerlessDeploymentBucketName
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionpuXaRLAxTKIYDIbesAM81p2p4unvd5aCvAFH7mdnxU
    Export:
      Name: sls-msCreateMVData-dev-FuncLambdaFunctionQualifiedArn
