AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msDeleteMedicalInfo
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msDeleteMedicalInfo/dev/1604583241620-2020-11-05T13:34:01.620Z/msDeleteMedicalInfo.zip
      FunctionName: msDeleteMedicalInfo
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      Runtime: nodejs12.x
      Timeout: 30
      Description: Microservi?o que exclui um recurso do DW
      Tags:
        - Key: api
          Value: ESBSamihealth
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:31'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:61'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersion9ZvYSoEtLKyWNwaOqh3L6jaj4cOxZRMkKU3Mgv5xEs:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: rq5N3rIfYVcgyrVsP9eLoMydnWXZGDedebBQWBJbncw=
      Description: Microservi?o que exclui um recurso do DW
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersion9ZvYSoEtLKyWNwaOqh3L6jaj4cOxZRMkKU3Mgv5xEs
