AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: /aws/lambda/msControlExportCingulo
  FuncLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      # Code:
      #   S3Bucket: sami-fhir-omop
      #   S3Key: >-
      #     serverless/msControlExportCingulo/dev/1659127332025-2022-07-29T20:42:12.025Z/msControlExportCingulo.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msControlExportCingulo
      MemorySize: 2048
      Timeout: 900
      Description: Microservi?o que faz o controle do envio de base para a Cingulo
      Tags:
        - Key: api
          Value: ESBSamihealth
      Role: "arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role"
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - "arn:aws:lambda:us-east-1:707583345549:layer:utils:70"
        - "arn:aws:lambda:us-east-1:707583345549:layer:pgknex:4"
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionPFJWhmR4G3RtHAKZ9kCnFtuoQpZn5OBFDPtoV87LUo:
    Type: "AWS::Lambda::Version"
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: ZX0QjHAlCAMitFqpCIlqQA2cT8VMaMdismR5CnwsK/g=
      Description: Microservi?o que faz o controle do envio de base para a Cingulo
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
    Export:
      Name: sls-msControlExportCingulo-dev-ServerlessDeploymentBucketName
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionPFJWhmR4G3RtHAKZ9kCnFtuoQpZn5OBFDPtoV87LUo
    Export:
      Name: sls-msControlExportCingulo-dev-FuncLambdaFunctionQualifiedArn
