AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msGetHaocData
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msGetHaocData
      MemorySize: 2048
      Timeout: 900
      Description: Microservi?o busca os atendimentos do RES do HAOC
      Tags:
        - Key: api
          Value: ESBSamihealth
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:66'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionQgfzoeh7lwchePRRw5tb0QMm5UUCoDjCdcgsEKG3cY:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: YjozL8c5IxvO0hyn6qXXGFr+6Yf6JbPgJey1anXyVxs=
      Description: Microservi?o busca os atendimentos do RES do HAOC
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
    Export:
      Name: sls-msGetHaocData-dev-ServerlessDeploymentBucketName
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionQgfzoeh7lwchePRRw5tb0QMm5UUCoDjCdcgsEKG3cY
    Export:
      Name: sls-msGetHaocData-dev-FuncLambdaFunctionQualifiedArn
