AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: /aws/lambda/msCreateMedicalInfo
  FuncLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msCreateMedicalInfo/dev/1622118570889-2021-05-27T12:29:30.889Z/msCreateMedicalInfo.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msCreateMedicalInfo
      MemorySize: 128
      Timeout: 60
      Description: Microservi?o que insere um recurso no DW
      Tags:
        - Key: api
          Value: ESBSamihealth
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Role: "arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role"
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - "arn:aws:lambda:us-east-1:707583345549:layer:utils:69"
        - "arn:aws:lambda:us-east-1:707583345549:layer:databaseOperator:37"

    DependsOn:
      - FuncLogGroup
  FuncLambdaVersion01kJzu6kAXu6o8etasFih2oruI0P9N3ZCRhb9sJzFY:
    Type: "AWS::Lambda::Version"
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: GiaBfyQ9UvLlCEeB1Z+Pc0bIThcj5cMhNjT3Usu7Za4=
      Description: Microservi?o que insere um recurso no DW
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersion01kJzu6kAXu6o8etasFih2oruI0P9N3ZCRhb9sJzFY
