AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  FuncLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/msImportEpisodeFromHSJ
  FuncLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: sami-fhir-omop
        S3Key: >-
          serverless/msImportEpisodeFromHSJ/dev/1649796677103-2022-04-12T20:51:17.103Z/msImportEpisodeFromHSJ.zip
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: msImportEpisodeFromHSJ
      MemorySize: 2048
      Timeout: 300
      Description: Microservi?o que recebe eventos do Hospital Santa Joana
      Tags:
        - Key: api
          Value: ESBSamihealth
      Role: 'arn:aws:iam::707583345549:role/aqr-sigma-fhir-rds-role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0619bafe5c30a779a
        SubnetIds:
          - subnet-0fc9788f19574469a
          - subnet-0ce006726d826405a
      Layers:
        - 'arn:aws:lambda:us-east-1:707583345549:layer:utils:70'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:got:1'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:fhirOmopConverter:159'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:databaseOps:36'
        - 'arn:aws:lambda:us-east-1:707583345549:layer:pgknex:4'
    DependsOn:
      - FuncLogGroup
  FuncLambdaVersionaWg9Qbie2WEXBdG9qjMnET8cfJv79gNdcfGhSO31Imo:
    Type: 'AWS::Lambda::Version'
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Ref FuncLambdaFunction
      CodeSha256: MQbzbyIjgrdOLSQB38I9JeqP6YgSpfU/twcQYPBvmJg=
      Description: Microservi?o que recebe eventos do Hospital Santa Joana
Outputs:
  ServerlessDeploymentBucketName:
    Value: sami-fhir-omop
    Export:
      Name: sls-msImportEpisodeFromHSJ-dev-ServerlessDeploymentBucketName
  FuncLambdaFunctionQualifiedArn:
    Description: Current Lambda function version
    Value: !Ref FuncLambdaVersionaWg9Qbie2WEXBdG9qjMnET8cfJv79gNdcfGhSO31Imo
    Export:
      Name: sls-msImportEpisodeFromHSJ-dev-FuncLambdaFunctionQualifiedArn
